version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached
      
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:database
    
    env_file:
      - .env


  database:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - motiv-api-core-database-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

  redis:
    image: redis:latest
    restart: unless-stopped
    volumes: 
      - motiv-api-core-redis-data:/data

volumes:
  motiv-api-core-database-data:
  motiv-api-core-redis-data: